### ISSUE TITLE
Incorrect package count in Alpine Linux

### ISSUE THREAD

**Issue by xplshn** [Un1q32/pfetch#11]
This happens when running under Alpine:
```
]@ /opt/AltSys/misc/bin/pfetch
   /\ /\          anto@pink
  // \  \         os@→      Alpine Linux edge
 //   \  \        host@→    VJF155A2011B
///    \  \       kernel@→  6.7.9-0-edge
//      \  \      uptime@→  6h 23m
         \        shell@→   ksh
                  term@→    xterm-256color
                  editor@→  ed
                  pkgs@→    290
                  memory@→  1194M / 3818M




]@ apk info | wc -l
251
]@
```

Here's some more info on my ENV and OS:
```
]@ export
BROWSER=elinks
CFLAGS='-march=native -O2 -static-pie -static'
CGO_ENABLED=0
CHARSET=UTF-8
COLORTERM=truecolor
COOLHOME=']'
COOLHOME_DEPTH=']'
COOLSPINNER='|/-\'
COOLSPINNER_COLOR='\033[32m'
DISPLAY=:0
EDITOR=ed
ENV=/home/anto/.shrc
GOBIN=/home/anto/.local/bin
GOCACHE=/home/anto/.cache/go
GOMPHOTHERIUM_SERVER=https://mastodon.bsd.cafe
GOROOT=/usr/local/go
GO_LDFLAGS='-extldflags "-static"'
HOME=/home/anto
LANG=C.UTF-8
LC_COLLATE=C
LDFLAGS=-static
LD_PRELOAD=/usr/lib/libswmhack.so.0.0
LOGNAME=anto
PAGER=less
PATH=/home/anto/.local/bin:/usr/local/go/bin:/usr/local/zig/bin:/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/AltSys/misc/bin
PF_COL1=4
PF_INFO='ascii title os host kernel uptime shell term editor pkgs memory palette'
PF_SEP=@→
PF_VERTP=0
POSIXLY_CORRECT=1
PWD=/home/anto
SHELL=ksh
SHLVL=6
SWM_STARTED=YES
TERM=xterm
TZDIR=/etc/zoneinfo
]@
```

**Comment by xplshn** [comment]
```
Another issue I found is:
Setting distro garbles output:
]@ distro="Andes" /opt/AltSys/misc/bin/pfetch
 os@Andes
    ___             anto@pink
   (.. |            os@→      Andes
   (<> |            host@→    VJF155A2011B
  / __  \           kernel@→  6.7.9-0-edge
 ( /  \ /|          uptime@→  6h 29m
_/\ __)/_)          shell@→   ksh
\/-____\/           term@→    xterm-256color
                    editor@→  ed
                    pkgs@→    290
                    memory@→  1322M / 3818M




]@
```

**Comment by xplshn** [comment]
Hmm, didn't think of that..? Yeah, I have cargo installed. How do I disable that then?

**Comment by Un1q32** [comment]
There is no way to disable individual package managers, I can try to add that tomorrow.

**Comment by xplshn** [comment]
Thanks, i'd appreciate it!

What about the bug with setting the "distro" var?

**Comment by Un1q32** [comment]
I have no idea, I'll look into it

**Comment by Un1q32** [comment]
I've added the ability to disable individual package managers with the `PF_DISABLED_PACKAGE_MANAGERS` environment variable, You can also see every package manager that contributes to the count by setting `PF_PACKAGE_MANAGERS=on`

**Comment by Un1q32** [comment]
As for the garbled output when setting the distro manually, it seems manually setting `$distro` was never intended and breaks things as a result.  I've added the environment variable `$PF_DISTRO` to manually set the distro properly

**Comment by xplshn** [comment]
Wow, cool! I will report back if I have any more problems! Thanks!

**Comment by Un1q32** [comment]
I've removed $PF_DISTRO because pfetch makes a lot of assumptions based on the value of $distro that could be wrong in other distros, I probobly should have known better then to add it in the first place.  If you want to set a different ASCII art use $PF_ASCII

**Comment by xplshn** [comment]
But now one can not change the displayed name... Is there not another way to simply change the displayed name? In my case I want to display: "Andes" instead of "Alpine 3.19"

**Comment by Un1q32** [comment]
I've added the `$PF_OS` and `$PF_HOST` config variables to override the output of os and host without breaking other parts of the script, note that `$PF_OS` does not affect the ASCII art like `$PF_DISTRO` used to.

**Comment by xplshn** [comment]
THanks!
