### ISSUE TITLE
use sw_vers -productVersion instead of plist

### ISSUE THREAD

**Issue by k2662** [Un1q32/pfetch#15]
we could use `sw_vers -productVersion` for os version info. like this: `mac_version=$(sw_vers -productVersion)`

**Comment by Un1q32** [comment]
How far back does `sw_vers` go?  is it in 10.4?

**Comment by k2662** [comment]
> How far back does `sw_vers` go? is it in 10.4?

yes

**Comment by Un1q32** [comment]
Do you know exactly when it was introduced?  or was it present since 10.0

**Comment by k2662** [comment]
> Do you know exactly when it was introduced? or was it present since 10.0

it was first present in exactly 10.4

**Comment by Un1q32** [comment]
Does the current method work in >=10.3?  I don't want to drop support for older versions just for slightly smaller code.

**Comment by k2662** [comment]
> Does the current method work in >=10.3? I don't want to drop support for older versions just for slightly smaller code.

wait actually it was first present in 10.2.1

**Comment by Un1q32** [comment]
So does the current method of getting the version work before then?

**Comment by k2662** [comment]
> So does the current method of getting the version work before then?

yes

**Comment by Un1q32** [comment]
I would rather just have one codebase to worry about
