### ISSUE TITLE
not showing correct macos version

### ISSUE THREAD

**Issue by k2662** [Un1q32/pfetch#16]
The plist file doesn't always show the correct version and the only way I can seem to get it to display the correct version is to use 
```sh
mac_version=$(sw_vers -productVersion)
```
otherwise it shows 10.16 which is Big Sur, but i'm on MacOS Ventura (13.6.6).
I made the fix here: https://github.com/k2662/pfetch

**Comment by Un1q32** [comment]
Try the latest commit

**Comment by k2662** [comment]
> Try the latest commit


Thank you! That fixed it
