### ISSUE TITLE
memory usage isn't accurate on macOS

### ISSUE THREAD

**Issue by k2662** [Un1q32/pfetch#17]
Pfetch isn't showing accurate memory usage.

**Comment by Un1q32** [comment]
what system are you on, memory is accurate for me

**Comment by k2662** [comment]
> what system are you on, memory is accurate for me

macos Ventura

**Comment by Un1q32** [comment]
On my macOS Sonoma machine pfetch's reported memory usage matches activity monitor's reported memory usage, interestingly htop and pfetch-rs seem to get it wrong.
