### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by yigitsever** [Un1q32/pfetch#18]
Hello,

I maintain pfetch at [Arch Linux User Repository ](https://aur.archlinux.org/packages/pfetch) and since the original repository is archived, I would like to set your fork as the new upstream.

I believe that your additions so far warrant a new release, which would help downstream maintainers like me bump numbers, notify users, pass the baton, etc. :)

Thank you for work

**Comment by Un1q32** [comment]
I've created a new 1.0.0 release
https://github.com/Un1q32/pfetch/releases/tag/1.0.0

**Comment by Un1q32** [comment]
I've released 1.0.1 to fix disk usage info not working in bash, I don't plan to release this frequently from now on, I just don't want the first big release to have one of the new features not work at all.

**Comment by yigitsever** [comment]
Thank you, I've updated the AUR package to use this fork
