### ISSUE TITLE
weird % symbol on terminal startup

### ISSUE THREAD

**Issue by k2662** [Un1q32/pfetch#19]
![image](https://github.com/Un1q32/pfetch/assets/120774884/0b2881b3-bc5b-4a40-8aa5-acc9333064b7)

**Comment by Un1q32** [comment]
Thats a problem with zsh IIRC, try running it from bash

**Comment by k2662** [comment]
> Thats a problem with zsh IIRC, try running it from bash


I use zsh for compatibility so, thats a problem

**Comment by Un1q32** [comment]
I believe it's an issue with zsh and your terminal.  I had it once and I think it was fixed when the terminal fixed it.  There's nothing I can do if it's a problem with zsh as pfetch doesn't even touch zsh.  Try opening bash and running pfetch from there and if it still happens then I'll look into it, but if it doesn't happen in bash then there's nothing I can do.

**Comment by Un1q32** [comment]
IIRC the % sign only showed up when opening a new terminal, regardless of if pfetch was run or not, it looks like you might be running pfetch automatically when you open a terminal (although it's hard to tell because the screenshot is poorly cropped)

I would suggest trying a different terminal and seeing if the issue persists, some good mac terminals besides Apple's built in one are [iTerm2](https://iterm2.com/) and [kitty](https://sw.kovidgoyal.net/kitty/)

**Comment by k2662** [comment]
> IIRC when I had this problem the % sign only showed up when opening a new terminal, regardless of if pfetch was run or not, it looks like you might be running pfetch automatically when you open a terminal (although it's hard to tell because the screenshot is poorly cropped)
> 
> I would suggest trying a different terminal and seeing if the issue persists, some good mac terminals besides Apple's built in one are [iTerm2](https://iterm2.com/) and [kitty](https://sw.kovidgoyal.net/kitty/). If you're already using a different terminal then Apple's included terminal I would suggest making sure your version of the terminal is up to date.

I use wezterm

**Comment by Un1q32** [comment]
if you run pfetch from bash in the default apple terminal does the % sign show up?

**Comment by k2662** [comment]
> if you run pfetch from bash in the default apple terminal does the % sign show up?

no, it doesn't show up.
The problem isn't zsh. the old pfetch before the fork work perfectly.

**Comment by Un1q32** [comment]
I installed wezterm and ran the latest pfetch release and latest commit in it on startup with zsh and couldn't reproduce the issue, Installing https://github.com/k2662/wezterm-dots still didn't help, does the issue still happen if you use a minimal zsh config?  Could you share what zsh config you use.

**Comment by k2662** [comment]
```sh
# Set correct terminfo directory
export TERMINFO=/private/etc/terminfo

# Fzf Completions
export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
--color=fg:-1,bg:-1,hl:#ea9a97
--color=fg+:#e0def4,bg+:#393552,hl+:#ea9a97
--color=border:#44415a,header:#3e8fb0,gutter:#232136
--color=spinner:#f6c177,info:#9ccfd8,separator:#44415a
--color=pointer:#c4a7e7,marker:#eb6f92,prompt:#908caa
'

# Disable the log builtin, so we don't conflict with /usr/bin/log
disable log

# Save command history
setopt promptsubst
HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt appendhistory

autoload -Uz compinit
compinit

ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_USE_ASYNC="true"

# autocd
setopt autocd

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Default prompt
PS1='%F{green}%1~>%f '

# Stuff
export LESS='-R --mouse --use-color -Dd+r$Du+b'
alias ls='ls --color=always'
alias grep='grep --color=always -n'
pfetch
eval "$(zoxide init zsh)"
export EDITOR=nvim
source /private/etc/fzf-tab/fzf-tab.zsh
zstyle ":completion:*:git-checkout:*" sort false
zstyle ':completion:*:descriptions' format '[%d]'
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 --color=always $realpath'
source /private/etc/zsh-custom/custom.plugin.zsh
source /private/etc/zsh-autopair/autopair.zsh
source /private/etc/zsh-autosuggestions/zsh-autosuggestions.zsh
source /private/etc/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /private/etc/zsh-history-substring-search/zsh-history-substring-search.zsh
```

**Comment by Un1q32** [comment]
Well if I can't reproduce it there's not much I can do.  If you can narrow down the exact commit the issue starts in then maybe I can help but otherwise you're on your own

**Comment by Un1q32** [comment]
FYI that the '195 commits ahead' is misleading as there was a reset at some point and a lot of the stuff even after that is garbage from when I didn't know what I was doing as much.  If you plan to narrow down the commit and you rule out everything after about a year ago then it might be easier to just use `diff` on that version to compare to the last commit from dylan and manually revert changes.
