### ISSUE TITLE
Code 4m fails somehow

### ISSUE THREAD

**Issue by polluks** [Un1q32/pfetch#25]
![image](https://github.com/Un1q32/pfetch/assets/4707573/8d600786-d5f4-45ed-96bd-0a90f28ada3b)

**Comment by Un1q32** [comment]
I can't get morph os to run in a VM, and I don't have any hardware capable of running it natively, so I can't reproduce this.  You'll have to fix it yourself and make a PR, or find a way it can be reproduced under another OS.

**Comment by polluks** [comment]
FYI version 1.4 did use a buggy ksh.
