### ISSUE TITLE
Tru64 UNIX

### ISSUE THREAD

**Issue by polluks** [Un1q32/pfetch#31]
```
$ /usr/bin/posix/sh pfetch
error: OSF1 is not currently supported.
error: Open an issue for support to be added.
$ uname -a
OSF1 truly V5.0 910 alpha
```
If you need a logo, see https://github.com/hykilpikonna/hyfetch/pull/218/files.

**Comment by Un1q32** [comment]
That logo was a bit big for pfetch, so I made my own based off this photo on the Tru64 UNIX wikipedia
https://en.wikipedia.org/wiki/Tru64_UNIX#/media/File:DigitalUNIX.jpg
