### ISSUE TITLE
HP-UX

### ISSUE THREAD

**Issue by polluks** [Un1q32/pfetch#32]
```
$ ./pfetch
error: HP-UX is not currently supported.
error: Open an issue for support to be added.
$ uname -a
HP-UX hkypux B.10.20 A 9000/715 2015454505 two-user license
```
https://github.com/AbhishekGhosh/HP-Cloud-ASCII-Logo/blob/master/HP-Cloud-ASCII-Logo.txt too big, I suppose

**Comment by Un1q32** [comment]
Added support, but the logo is terrible because I couldn't come up with a good design without going too big.  If you come up with something better I'll add it.

**Comment by polluks** [comment]
By the way ask ChatGPT for HP-UX as ASCII art :-D

**Comment by Un1q32** [comment]
![image](https://github.com/user-attachments/assets/5ddc45e9-fbe1-4163-9f40-2219f8eb8780)
