### ISSUE TITLE
Haiku: disk

### ISSUE THREAD

**Issue by polluks** [Un1q32/pfetch#41]
https://github.com/Un1q32/pfetch/blob/5424c5df74931387882cfa4001f633b45497d7f3/pfetch#L1231
I cannot see the oddness
https://www.markround.com/blog/2023/02/13/haiku-package-management/#filesystem-layout

**Comment by Un1q32** [comment]
<img width="953" alt="Screenshot 2024-09-03 at 8 22 58 AM" src="https://github.com/user-attachments/assets/9ed04654-b8e3-4a02-a246-e2cecd50512e">

The info we need is total disk space, used disk space, and the percentage used.  Haiku df doesn't provide enough info.

**Comment by polluks** [comment]
Sorry, I don't see the point
```
$ a=232.9; b=219.6; a=${a%.*}; b=${b%.*}; c=$((a - b))
$ echo $c / $b \($((c * 100 / a))%\)
13 / 219 (5%)

**Comment by Un1q32** [comment]
I don't like the inaccuracy from having to drop decimals, but I guess it's fine.

**Comment by Un1q32** [comment]
What is the full output from `df -h /`?

**Comment by polluks** [comment]
Right now I have just the source handy https://github.com/haiku/haiku/blob/master/src/bin/df.cpp

**Comment by Un1q32** [comment]
Got a VM running, output is wildly different so I had to write a parser just for it.  I also reworked the part that converts Digital UNIX/IRIX df output to human readable format to be able to display fractions, so that output should be better now.  LMK if it works on your system.

**Comment by polluks** [comment]
perfect!
