### ISSUE TITLE
significant slowdown

### ISSUE THREAD

**Issue by chimps-ahoy** [Un1q32/pfetch#42]
I noticed that my fetch (which is in my .bashrc so launches with each shell) has significantly slowed down since a system update a few weeks(?) ago. I looked through the commits and narrowed it down to commit `f13d3f5 - Add support for more package managers`.

I have timed both the latest version as well as the version of the script just before this commit. (`b3597d7 - fix hp thing`) using the `time` builtin of `bash`. Here are the results.

Latest commit:
```
real    0m0.204s
user    0m0.170s
sys 0m0.036s
```

at `b3597d7`:
```
real    0m0.028s
user    0m0.016s
sys 0m0.014s
```

I'd like to get this fixed because the speed difference is very noticable and annoying for me. I hope it shouldn't be too hard because I've identified the exact commit. I can take some time to try and find the slowdown myself, and will do so if I don't hear back on this issue shortly.
 
Thanks :D

**Comment by chimps-ahoy** [comment]
UPDATE:
update to this, turns out I was able to find the slowdown quite quickly after this. There difference in time is exactly the time it takes to run 'pip freeze', so I can fix this for myself by using 'PF_DISABLED_PACKAGE_MANAGERS=pip'.

I will close this issue because nothing needs to be done about this, but it does make me wonder why pip is so slow !

**Comment by KaKi87** [comment]
@Un1q32 Considering the slowness of counting pip packages, I would like to suggest either disabling it by default or finding a faster way to do it. Thanks

**Comment by Un1q32** [comment]
I've disabled pip by default and added a PF_ENABLE_SLOW_PACKAGE_MANAGERS config option to reenable slow package managers.  Other package managers that take more than about half a second should be guarded behind this option too.
