### ISSUE TITLE
What about AIX?

### ISSUE THREAD

**Issue by polluks** [Un1q32/pfetch#43]
https://github.com/Un1q32/pfetch/blob/165b2d27dc79b83943a08f833752bdb42a002097/pfetch#L1204
```
# uname -a
AIX 000000000000 2 7 000000000000
# df -P
Filesystem    512-blocks      Used Available Capacity Mounted on
/dev/ram0         393216    288592    104624      74% /
/dev/ramdisk0    1048576     33016   1015560       4% /mnt
/mnt             1048576     33016   1015560       4% /tmp

**Comment by polluks** [comment]
It was no so easy...
```
    __    __ _    _    @unknown
   /_ \   || \  //     os         AIX 2
  //_\ \  ||  \//      host       000000000000
 / ___  \ ||  //\      kernel     2
/_/   \__\|| //  \

**Comment by Un1q32** [comment]
username issue should be fixed with a fallback to "unknown" just like the hostname.

The other error is from get_uptime, `$s` is supposed to be the total number of seconds of uptime, but it was unset since no uptime calculation method existed.  I've added a check for that to suppress the warning.
