### ISSUE TITLE
Support for custom ASCII art

### ISSUE THREAD

**Issue by Ingvix** [Un1q32/pfetch#49]
I would like some method to use custom ASCII art with pfetch. The art I'd like to use is rather personally significant so I don't think it would make much sense making a PR to add it to the project. Not sure what would be the best way to implement it. The options that come to my mind are reading from STDIN, reading it raw from an enviroment variable, reading it from a file that's given in a environment variable, or executing a command that's saved to a environment variable and reading its output.

**Comment by Un1q32** [comment]
This ended up being a lot easier to implement then I thought it would be.  The read_ascii() function already reads text from stdin, I just had to make it read a file instead.

You can use custom ASCII art by setting `$PF_CUSTOM_ASCII` to the path of a text file containing your ASCII art.  Note that you can't use the normal `$c1-9` variables to control color, so you'll have to add the raw escape sequences instead.

**Comment by Ingvix** [comment]
That was fast. Thanks a lot!
