### ISSUE TITLE
Man page?

### ISSUE THREAD

**Issue by danielhejduk** [Un1q32/pfetch#50]
Hello @Un1q32, I maintain a Alpine linux package of your pfetch fork. I think it can be good to have a man page. I can make a PR if you agree.

Best regards
Daniel Hejduk

**Comment by Un1q32** [comment]
Good idea! Every environment variable is documented in the readme so you can copy that, and the only command line options are -d/--debug and -v/--version.

```
pfetch     show system information
pfetch -d  debug mode
pfetch -v  show version
```

**Comment by danielhejduk** [comment]
I recommend to make new release of pfetch, so I can update the alpine linux package. Maybe we can do config files like neofetch.

**Comment by Un1q32** [comment]
I make a new release the 1st of every month.  The next release will be on November 1st.

**Comment by danielhejduk** [comment]
OK

**Comment by Un1q32** [comment]
I've made that new release btw

**Comment by danielhejduk** [comment]
The PR is live. https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/74513
